version: "3.7"
services:
  mthesis-postgres:
    image: postgres:12.10
    container_name: mthesis-postgres
    restart: always
    environment:
      - POSTGRES_USER=mthesis_u
      - POSTGRES_PASSWORD=mthesis_p
      - POSTGRES_DB=mthesis_db
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


# Commands to build and run the composition
#   docker-compose up
