version: "3.7"

services:

  m-thesis-db:
    image: postgres:12.10
    container_name: m-thesis-db
    restart: always
    environment:
      - POSTGRES_USER=mthesis_u
      - POSTGRES_PASSWORD=mthesis_p
      - POSTGRES_DB=mthesis_db
    ports:
      - '5438:5432'
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data

  m-thesis-server-side:
    container_name: m-thesis-server-side
    build:
      context: ./server-side
      dockerfile: Dockerfile-prod
    # Run in debug mode: yarn run start:debug
    # Run in dev mode: yarn run start:dev
    depends_on:
      - m-thesis-db
    ports:
      - '8080:3000'
    command: >
      sh -c "yarn db:restart &&
             yarn start:prod"


# Commands to build and run the composition
#   docker-compose -f docker-compose.prod.yml build
#   docker-compose -f docker-compose.prod.yml up
