version: "3.7"

services:

  mwd-postgres:
    image: postgres:12.10
    container_name: mwd-postgres
    restart: always
    environment:
      - POSTGRES_USER=mwd_u
      - POSTGRES_PASSWORD=mwd_p
      - POSTGRES_DB=mwd_db
    ports:
      - '5438:5432'
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data

  mwd-prisma-db-init:
    container_name: mwd-prisma-db-init
    build:
      context: ./prisma-tools
      dockerfile: Dockerfile
    command: yarn prisma:up
    depends_on:
      - mwd-postgres

  mwd-server-side:
    container_name: mwd-server-side
    build:
      context: ./server-side
      dockerfile: Dockerfile-prod
    # Run in debug mode: yarn run start:debug
    # Run in dev mode: yarn run start:dev
    depends_on:
      - mwd-postgres
      - mwd-prisma-db-init
    ports:
      - '8080:3000'
    command: >
      sh -c "yarn start:prod"

  mwd-client-side-rest:
    container_name: mwd-client-side-rest
    build:
      context: ./client-side-rest
      dockerfile: Dockerfile
      target: production
    depends_on:
      - mwd-postgres
      - mwd-prisma-db-init
      - mwd-server-side
    ports:
      - '3100:3010'

  mwd-client-side-graphql:
    container_name: mwd-client-side-graphql
    build:
      context: ./client-side-graphql
      dockerfile: Dockerfile
      target: production
    depends_on:
      - mwd-postgres
      - mwd-prisma-db-init
      - mwd-server-side
    ports:
      - '3200:3020'

# Commands to build and run the composition
#   docker-compose -f docker-compose.prod.yml build
#   docker-compose -f docker-compose.prod.yml up
