version: "3.7"

services:

  m-thesis-db:
    image: postgres:12.10
    container_name: m-thesis-db
    restart: always
    environment:
      - POSTGRES_USER=mthesis_u
      - POSTGRES_PASSWORD=mthesis_p
      - POSTGRES_DB=mthesis_db
    ports:
      - '5438:5432'
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data

  m-thesis-server-side:
    container_name: m-thesis-server-side
    build:
      context: ./server-side
      dockerfile: Dockerfile
    # Mount our host directory to the docker container
    # Mount api directory (./server-side) to (:) docker container (/usr/src/app)
    # Reflect host file changes within the container
    volumes:
      - ./server-side:/usr/m-thesis/app
    # Run in debug mode: yarn run start:debug
    # Run in dev mode: yarn run start:dev
    depends_on:
      - m-thesis-db
    expose:
      - '3000'
    ports:
      - '8080:3000'
    command: >
      sh -c "yarn &&
             yarn db:restart &&
             yarn start:dev
            "

  prisma-studio:
    container_name: prisma-studio
    build:
      context: ./server-side/prisma
      dockerfile: Dockerfile
    depends_on:
      - m-thesis-server-side
    ports:
      - '5555:5555'
    command: yarn prisma studio


# Commands to build and run the composition
#   docker-compose build
#   docker-compose up
