##########################################
#               PRODUCTION
##########################################

# Build production image
FROM node:16

# Specify our working directory, this is in our container/in our image
WORKDIR /usr/mthesis/app

# Set node env to prod
ARG NODE_ENV=prod
ENV NODE_ENV=${NODE_ENV}

# Copy the package.jsons from host to container
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN yarn

# Bundle all app source files into the container
COPY . .

# Build the app into the /dist folder
RUN yarn build

EXPOSE 3000


# Example Commands to build and run this dockerfile
#   sudo docker build . -t petr-pondelik/master-thesis-server-side
#   sudo docker run -p 8080:3000 petr-pondelik/master-thesis-server-side
